// GENERATED by App\Services\AdStudio\AdProjectBuilder. Reads the interval list
// the studio wrote to assets/audio/tones.json and synthesizes every tone the cut
// needs.
//
// The quiz has to actually sound, and it has to be in tune — no catalog SFX
// substitutes for that. These are additive-synth tones (harmonic stack +
// per-partial exponential decay + a short attack), which reads convincingly as a
// struck keyboard at this length and stays fully deterministic: same bytes on
// every run, which is what keeps a re-render identical.
//
// Every round is rooted on A4 so a difficulty ramp is heard as the INTERVAL
// changing, not the register moving.
//
//   q-<slug>.wav  the two notes melodically, MELODIC_GAP apart — the question
//   r-<slug>.wav  the same two pitches together — the answer as one colour
//   correct.wav   the answer ping for the product frame's tap
//   sting.wav     a low tritone dyad — the verdict hit under the final answer
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const RATE = 48000;
const OUT_DIR = "assets/audio";
const ROOT = 440.0; // A4

// Load-bearing: three frame timelines land their second note head on exactly
// this offset, and AdTimingPlanner::MELODIC_GAP must match it.
const MELODIC_GAP = 0.85;

// Relative amplitude + decay rate per harmonic. Fast-decaying upper partials are
// what make it read as a struck string rather than an organ.
const PARTIALS = [
  { mult: 1, amp: 1.0, decay: 2.6 },
  { mult: 2, amp: 0.42, decay: 3.8 },
  { mult: 3, amp: 0.2, decay: 5.0 },
  { mult: 4, amp: 0.11, decay: 6.4 },
  { mult: 6, amp: 0.05, decay: 8.0 },
];

const semitonesToHz = (root, n) => root * Math.pow(2, n / 12);

function addNote(buffer, freq, startSec, gain = 0.5, lengthSec = 1.9) {
  const start = Math.floor(startSec * RATE);
  const total = Math.min(Math.floor(lengthSec * RATE), buffer.length - start);
  for (let i = 0; i < total; i++) {
    const t = i / RATE;
    // 6ms attack ramp removes the click a hard start would leave.
    const attack = Math.min(1, t / 0.006);
    let sample = 0;
    for (const p of PARTIALS) {
      sample += p.amp * Math.exp(-p.decay * t) * Math.sin(2 * Math.PI * freq * p.mult * t);
    }
    buffer[start + i] += sample * attack * gain;
  }
}

function writeWav(path, buffer) {
  // Normalize to -1.5 dBFS so mixing against the narration is predictable.
  let peak = 0;
  for (const s of buffer) peak = Math.max(peak, Math.abs(s));
  const scale = peak > 0 ? 0.84 / peak : 1;

  const pcm = Buffer.alloc(buffer.length * 2);
  for (let i = 0; i < buffer.length; i++) {
    const clamped = Math.max(-1, Math.min(1, buffer[i] * scale));
    pcm.writeInt16LE(Math.round(clamped * 32767), i * 2);
  }
  const header = Buffer.alloc(44);
  header.write("RIFF", 0);
  header.writeUInt32LE(36 + pcm.length, 4);
  header.write("WAVE", 8);
  header.write("fmt ", 12);
  header.writeUInt32LE(16, 16);
  header.writeUInt16LE(1, 20);
  header.writeUInt16LE(1, 22);
  header.writeUInt32LE(RATE, 24);
  header.writeUInt32LE(RATE * 2, 28);
  header.writeUInt16LE(2, 32);
  header.writeUInt16LE(16, 34);
  header.write("data", 36);
  header.writeUInt32LE(pcm.length, 40);
  writeFileSync(path, Buffer.concat([header, pcm]));
  console.log(`${path} — ${(buffer.length / RATE).toFixed(2)}s`);
}

const silence = (sec) => new Float64Array(Math.floor(sec * RATE));

mkdirSync(OUT_DIR, { recursive: true });

const spec = JSON.parse(readFileSync(join(OUT_DIR, "tones.json"), "utf8"));

// De-duplicated: two rounds may legitimately ask the same interval, and there is
// no reason to synthesize it twice.
const seen = new Set();
for (const round of spec.rounds) {
  if (seen.has(round.slug)) continue;
  seen.add(round.slug);

  const upper = semitonesToHz(ROOT, round.semitones);

  // Question: two notes, melodic, clearly separated so the ear can measure the step.
  const quiz = silence(2.6);
  addNote(quiz, ROOT, 0.0, 0.55);
  addNote(quiz, upper, MELODIC_GAP, 0.55);
  writeWav(join(OUT_DIR, `q-${round.slug}.wav`), quiz);

  // Answer: the same two pitches sounded together — the interval as one colour.
  const reveal = silence(2.2);
  addNote(reveal, ROOT, 0.0, 0.4, 2.1);
  addNote(reveal, upper, 0.0, 0.4, 2.1);
  writeWav(join(OUT_DIR, `r-${round.slug}.wav`), reveal);
}

// Correct-answer ping for the product frame's tap: G5 then C6 (+10, +15 from the
// A4 root). A rising fourth — unambiguously "yes" without being a UI blip.
const correct = silence(1.3);
addNote(correct, semitonesToHz(ROOT, 10), 0.0, 0.34, 0.7);
addNote(correct, semitonesToHz(ROOT, 15), 0.11, 0.4, 1.1);
writeWav(join(OUT_DIR, "correct.wav"), correct);

// The verdict hit under the final answer: a tritone two octaves down, where the
// interval stops being a label and starts being a sound you flinch at.
const sting = silence(1.8);
addNote(sting, semitonesToHz(ROOT, -24), 0.0, 0.62, 1.7);
addNote(sting, semitonesToHz(ROOT, -18), 0.0, 0.62, 1.7);
writeWav(join(OUT_DIR, "sting.wav"), sting);
